export const host = "https://api.klarfin.com/";

export const industries = [
  "Hospitality",
  "Education",
  "Agri",
  "Construction, Real Estate",
  "Health services",
  "Manufacturing",
  "Restaurant/Bars/Catering",
  "Retail - Primarily online",
  "Retail - Primarily offline",
  "Legal services",
  "Other",
  "Technology",
  "Media, Advertising, Entertainment",
  "Finance",
  "Transportation",
  "Health & wellness",
  "Consulting",
  "Logistics",
  "Fashion",
  "Ecommerce",
  "Travel",
];
